# Antigravity Template Setup Script
# Run from: C:\Users\mneub\Documents\GitHub\anti-gravity-template

# Create directory structure
$dirs = @(
    ".agent\rules",
    ".agent\skills\fastapi-dev",
    ".agent\skills\react-frontend",
    ".agent\skills\testing",
    ".agent\skills\homelab-ops",
    ".agent\skills\docker-deploy",
    "docs"
)
foreach ($d in $dirs) {
    New-Item -ItemType Directory -Path $d -Force | Out-Null
}

# ── GEMINI.md ──
@'
# Project Rules — Antigravity

> These rules override AGENTS.md when running inside Antigravity.
> For cross-tool rules shared with Cursor / Claude Code, see AGENTS.md.

## Identity

- You are an expert Python/TypeScript full-stack engineer.
- You work on projects owned by Michael Neuberger (neubneub01 on GitHub).
- Always plan before coding. Generate a `task.md` artifact first.

## Code Style

- Python: Follow PEP 8. Use type hints everywhere. Prefer `snake_case`.
- TypeScript/React: Functional components only. Prefer named exports.
- All functions must have docstrings or JSDoc comments.
- Never use `any` in TypeScript. Never use bare `except` in Python.

## Architecture Preferences

- Backend: FastAPI + Pydantic v2 + SQLAlchemy 2.0 async.
- Frontend: React 18+ with TypeScript. Tailwind CSS for styling.
- Testing: pytest with pytest-asyncio for Python. Vitest for TS.
- Always use dependency injection patterns in FastAPI.
- Always define Pydantic models for request/response schemas.

## Git & PR Workflow

- Commit messages: conventional commits (`feat:`, `fix:`, `docs:`, `chore:`).
- Branch naming: `feat/short-description`, `fix/short-description`.
- Always include a "Security Implications" section in implementation plans.

## Design Style

- Clean, minimal UI. No glassmorphism or excessive animation.
- Use a consistent color palette defined in tailwind.config.ts.
- Mobile-first responsive design.

## Safety

- Never hardcode secrets, API keys, or credentials.
- Never run destructive commands (`rm -rf`, `DROP DATABASE`) without explicit approval.
- Never push directly to `main`.
'@ | Set-Content -Path "GEMINI.md" -Encoding UTF8

# ── AGENTS.md ──
@'
# Cross-Tool Agent Rules

> Shared rules read by Antigravity, Cursor, and Claude Code.
> Antigravity-specific overrides go in GEMINI.md.

## General

- Respond concisely. No filler text.
- When uncertain, ask before assuming.
- Always check for existing patterns in the codebase before introducing new ones.

## Python Conventions

- Python 3.11+ minimum.
- Use `pathlib.Path` over `os.path`.
- Use `httpx` over `requests` for async HTTP.
- Prefer f-strings over `.format()`.
- Use `logging` module, never `print()` for diagnostics.

## TypeScript Conventions

- Strict mode enabled. No implicit any.
- Prefer `const` over `let`. Never `var`.
- Use `zod` for runtime validation on the frontend.

## Infrastructure

- Docker Compose for local dev. Multi-stage Dockerfiles for prod.
- Environment variables via `.env` files (never committed).
- All services must have health check endpoints.

## Documentation

- Every project must have a README.md with: purpose, setup, architecture, and contributing sections.
- API endpoints must be documented via OpenAPI (auto-generated by FastAPI).
'@ | Set-Content -Path "AGENTS.md" -Encoding UTF8

# ── .agent/rules/01-project-context.md ──
@'
---
description: "Core project context and architecture. Always active."
activation: always
---

# Project Context

<!-- CUSTOMIZE: Replace this section per-project -->

## Project Name
<!-- e.g., fitness-neub -->

## Tech Stack
<!-- e.g., FastAPI 0.115+, Python 3.12, SQLAlchemy 2.0, React 18, TypeScript 5 -->

## Directory Layout
```
src/
├── api/          # FastAPI routers
├── core/         # Config, security, deps
├── models/       # SQLAlchemy models
├── schemas/      # Pydantic schemas
├── services/     # Business logic
├── tests/        # pytest suite
frontend/
├── src/
│   ├── components/
│   ├── hooks/
│   ├── pages/
│   └── lib/
```

## Key Patterns
- All routers use dependency injection for DB sessions.
- Business logic lives in `services/`, never in routers.
- Pydantic schemas separate Create/Update/Response variants.
'@ | Set-Content -Path ".agent\rules\01-project-context.md" -Encoding UTF8

# ── .agent/rules/02-python-standards.md ──
@'
---
description: "Python-specific coding standards. Applied to Python files."
activation: glob
glob: "**/*.py"
---

# Python Standards

- All functions must have type hints for parameters AND return types.
- Use `Annotated[type, Depends(...)]` for FastAPI dependency injection.
- Async functions for all I/O-bound operations.
- Use `contextlib.asynccontextmanager` for resource lifecycle.
- Models inherit from a shared `Base` with `created_at` / `updated_at` mixins.
- Never use mutable default arguments.
- Prefer `match/case` over long if/elif chains (Python 3.10+).
'@ | Set-Content -Path ".agent\rules\02-python-standards.md" -Encoding UTF8

# ── .agent/rules/03-typescript-standards.md ──
@'
---
description: "TypeScript and React standards. Applied to TS/TSX files."
activation: glob
glob: "**/*.{ts,tsx}"
---

# TypeScript & React Standards

- Functional components only. No class components.
- Use named exports: `export function MyComponent() {}`.
- Props interfaces named `{ComponentName}Props`.
- Custom hooks prefixed with `use` and placed in `hooks/`.
- Use `React.Suspense` and lazy loading for route-level code splitting.
- Error boundaries around all async data-fetching components.
- Use Tailwind utility classes. No inline styles. No CSS modules.
'@ | Set-Content -Path ".agent\rules\03-typescript-standards.md" -Encoding UTF8

# ── .agent/skills/fastapi-dev/SKILL.md ──
@'
---
name: fastapi-dev
description: |
  Use when creating new FastAPI endpoints, routers, services, or Pydantic schemas.
  Triggers on: "add endpoint", "new route", "create API", "CRUD", "service layer",
  "pydantic model", "schema", "FastAPI".
---

# FastAPI Development Skill

## When to Use
When the user asks to create, modify, or scaffold any FastAPI backend component.

## Workflow

1. **Schema First**: Define Pydantic request/response schemas in `src/schemas/`.
   - Use `Create`, `Update`, `Response` suffixes.
   - Example: `WorkoutCreate`, `WorkoutUpdate`, `WorkoutResponse`.

2. **Service Layer**: Implement business logic in `src/services/`.
   - Services accept a `AsyncSession` parameter.
   - Services return domain objects, never HTTP responses.

3. **Router**: Wire up in `src/api/`.
   - Use `APIRouter(prefix="/resource", tags=["resource"])`.
   - Inject dependencies with `Annotated[AsyncSession, Depends(get_db)]`.
   - Return appropriate status codes (201 for create, 204 for delete).

4. **Tests**: Create matching test file in `src/tests/`.
   - Use `httpx.AsyncClient` with the FastAPI `TestClient`.
   - Test happy path, validation errors, and not-found cases.

## Template: New Router

```python
from typing import Annotated
from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.ext.asyncio import AsyncSession

from src.core.deps import get_db
from src.schemas.{resource} import {Resource}Create, {Resource}Response
from src.services.{resource} import {Resource}Service

router = APIRouter(prefix="/{resources}", tags=["{resources}"])

@router.post("/", response_model={Resource}Response, status_code=status.HTTP_201_CREATED)
async def create_{resource}(
    data: {Resource}Create,
    db: Annotated[AsyncSession, Depends(get_db)],
) -> {Resource}Response:
    service = {Resource}Service(db)
    return await service.create(data)
```

## Constraints
- Never put business logic in routers.
- Never return raw SQLAlchemy models from endpoints.
- Always validate with Pydantic before hitting the DB.
'@ | Set-Content -Path ".agent\skills\fastapi-dev\SKILL.md" -Encoding UTF8

# ── .agent/skills/react-frontend/SKILL.md ──
@'
---
name: react-frontend
description: |
  Use when building React components, pages, hooks, or frontend features.
  Triggers on: "component", "page", "UI", "frontend", "React", "form",
  "dashboard", "hook", "Tailwind".
---

# React Frontend Skill

## Component Structure

```
frontend/src/
├── components/     # Reusable UI components
│   └── ui/         # Primitives (Button, Input, Card)
├── hooks/          # Custom hooks
├── pages/          # Route-level page components
├── lib/            # Utilities, API client, types
└── App.tsx         # Root with router
```

## New Component Checklist

1. Create file: `components/{ComponentName}.tsx`
2. Define props interface: `{ComponentName}Props`
3. Use named export
4. Add loading/error states for data-fetching components
5. Responsive by default (mobile-first Tailwind)

## API Integration Pattern

```typescript
const API_BASE = import.meta.env.VITE_API_URL ?? "http://localhost:8000";

export async function apiFetch<T>(path: string, init?: RequestInit): Promise<T> {
  const res = await fetch(`${API_BASE}${path}`, {
    headers: { "Content-Type": "application/json", ...init?.headers },
    ...init,
  });
  if (!res.ok) throw new Error(`API ${res.status}: ${await res.text()}`);
  return res.json();
}
```

## Custom Hook Pattern

```typescript
export function use{Resource}() {
  const [data, setData] = useState<{Resource}[] | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<Error | null>(null);

  useEffect(() => {
    apiFetch<{Resource}[]>("/{resources}")
      .then(setData)
      .catch(setError)
      .finally(() => setLoading(false));
  }, []);

  return { data, loading, error };
}
```

## Constraints
- No `any` types.
- No inline styles — Tailwind only.
- Forms use controlled components with `zod` validation.
'@ | Set-Content -Path ".agent\skills\react-frontend\SKILL.md" -Encoding UTF8

# ── .agent/skills/testing/SKILL.md ──
@'
---
name: testing
description: |
  Use when writing tests, debugging test failures, or setting up test infrastructure.
  Triggers on: "test", "pytest", "vitest", "coverage", "fixture", "mock",
  "test suite", "TDD", "assert".
---

# Testing Skill

## Python (pytest)

### File Naming
- `tests/test_{module}.py` mirrors `src/{module}.py`

### Fixtures in `conftest.py`
```python
import pytest_asyncio
from httpx import ASGITransport, AsyncClient
from src.main import app

@pytest_asyncio.fixture
async def client():
    async with AsyncClient(transport=ASGITransport(app=app), base_url="http://test") as ac:
        yield ac
```

### Test Structure (Arrange-Act-Assert)
```python
async def test_create_resource(client: AsyncClient):
    # Arrange
    payload = {"name": "Test", "value": 42}
    # Act
    response = await client.post("/resources/", json=payload)
    # Assert
    assert response.status_code == 201
    data = response.json()
    assert data["name"] == "Test"
```

### Coverage
- Run: `pytest --cov=src --cov-report=term-missing`
- Target: 80%+ line coverage.

## TypeScript (Vitest)

### Test Structure
```typescript
import { describe, it, expect } from "vitest";

describe("formatCurrency", () => {
  it("formats USD correctly", () => {
    expect(formatCurrency(1234.5, "USD")).toBe("$1,234.50");
  });
});
```

## Constraints
- Every new endpoint needs at least: happy path, 422 validation, 404 not-found tests.
- Never mock what you can test directly.
- Tests must be deterministic — no reliance on wall-clock time.
'@ | Set-Content -Path ".agent\skills\testing\SKILL.md" -Encoding UTF8

# ── .agent/skills/homelab-ops/SKILL.md ──
@'
---
name: homelab-ops
description: |
  Use when working with homelab infrastructure, Proxmox, Docker containers,
  Tailscale, Cloudflare tunnels, or self-hosted services.
  Triggers on: "homelab", "proxmox", "container", "LXC", "VM",
  "tailscale", "cloudflare tunnel", "self-host", "deploy to homelab".
---

# Homelab Operations Skill

## Environment

- **Cluster**: 2-node Proxmox (source of truth: neubneub01/homelab repo — private)
- **Networking**: Tailscale mesh + Cloudflare tunnels for public endpoints.
- **Services**: Plex, *arr stack, Navidrome, n8n, Home Assistant, Grafana, Frigate.
- **DNS**: Cloudflare.

## CRITICAL
- **NEVER rely on stale memory for IPs, node assignments, or container details.**
- Always ask the user to paste or upload current repo contents if needed.
- Older context referencing 3 nodes is STALE — there are 2 nodes.

## Container Deployment Checklist

1. Define service in `docker-compose.yml` with:
   - `restart: unless-stopped`
   - Health check
   - Named volume for persistent data
   - Environment variables via `.env` file
2. Expose via Cloudflare tunnel OR Tailscale only — never direct port exposure.
3. Add to monitoring (Grafana dashboard / Uptime Kuma).
4. Document in homelab repo README.

## Safety
- Never run destructive Proxmox commands (`pct destroy`, `qm destroy`) without confirmation.
- Always snapshot before major changes.
- Never expose management interfaces (Proxmox UI, Portainer) publicly.
'@ | Set-Content -Path ".agent\skills\homelab-ops\SKILL.md" -Encoding UTF8

# ── .agent/skills/docker-deploy/SKILL.md ──
@'
---
name: docker-deploy
description: |
  Use when creating Dockerfiles, docker-compose configs, or deploying
  containerized applications.
  Triggers on: "docker", "Dockerfile", "compose", "container", "image",
  "build", "deploy", "multi-stage".
---

# Docker Deployment Skill

## Dockerfile Pattern (Python/FastAPI)

```dockerfile
# --- Build stage ---
FROM python:3.12-slim AS builder
WORKDIR /app
COPY pyproject.toml uv.lock ./
RUN pip install uv && uv sync --frozen --no-dev

# --- Runtime stage ---
FROM python:3.12-slim
WORKDIR /app
COPY --from=builder /app/.venv /app/.venv
COPY src/ src/
ENV PATH="/app/.venv/bin:$PATH"
EXPOSE 8000
HEALTHCHECK --interval=30s --timeout=5s CMD curl -f http://localhost:8000/health || exit 1
CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]
```

## docker-compose Pattern

```yaml
services:
  app:
    build: .
    restart: unless-stopped
    env_file: .env
    ports:
      - "${APP_PORT:-8000}:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    volumes:
      - app_data:/app/data

volumes:
  app_data:
```

## Constraints
- Always use multi-stage builds to minimize image size.
- Pin base image versions (e.g., `python:3.12-slim`, not `python:latest`).
- Never copy `.env`, `.git`, or `node_modules` into images — use `.dockerignore`.
- Always include a health check.
'@ | Set-Content -Path ".agent\skills\docker-deploy\SKILL.md" -Encoding UTF8

# ── docs/ADDING_SKILLS.md ──
@'
# Adding Custom Skills

## Minimal Skill

Create a folder under `.agent/skills/` with a `SKILL.md`:

```
.agent/skills/my-skill/
└── SKILL.md
```

### SKILL.md Template

```markdown
---
name: my-skill
description: |
  1-2 sentences describing WHEN this skill should activate.
  Include trigger keywords the agent will match against.
---

# My Skill Name

## When to Use
Describe the scenario clearly.

## Steps
1. Step one
2. Step two

## Template (optional)
Code template the agent should follow.

## Constraints
- What NOT to do.

## Examples (optional)
Input -> Output examples help the agent learn the pattern.
```

## Key Tips

- **Description is SEO for the AI** — be specific with trigger words.
- **Atomic design** — one skill per concern.
- **Include constraints** — tell the agent what NOT to do.
- **Add scripts** if the skill needs to execute something.

## Activation

Skills are loaded on-demand via semantic matching against the `description` field.
Restart the agent after adding new skills: `Cmd/Ctrl+Shift+P` -> "Restart Agent".
'@ | Set-Content -Path "docs\ADDING_SKILLS.md" -Encoding UTF8

# ── .gitignore ──
@'
.env
.env.*
!.env.example
__pycache__/
*.pyc
.venv/
dist/
*.egg-info/
node_modules/
.vscode/
.idea/
.DS_Store
Thumbs.db
.agent/knowledge/
.agent/conversations/
'@ | Set-Content -Path ".gitignore" -Encoding UTF8

# ── README.md ──
@'
# Antigravity Project Template

Modular, reusable Google Antigravity configuration for Python/TypeScript full-stack projects.

## Quick Start

1. Edit `.agent/rules/01-project-context.md` with your project details
2. Delete any skills you don't need from `.agent/skills/`
3. Open this folder in Antigravity

## Structure

```
.
├── GEMINI.md                          # Antigravity rules (highest priority)
├── AGENTS.md                          # Cross-tool rules (Cursor, Claude Code)
├── .agent/
│   ├── rules/                         # Always-active & glob-triggered rules
│   │   ├── 01-project-context.md      # ← CUSTOMIZE THIS per project
│   │   ├── 02-python-standards.md     # Auto-applies to *.py
│   │   └── 03-typescript-standards.md # Auto-applies to *.ts/*.tsx
│   └── skills/                        # On-demand skills
│       ├── fastapi-dev/SKILL.md
│       ├── react-frontend/SKILL.md
│       ├── testing/SKILL.md
│       ├── homelab-ops/SKILL.md
│       └── docker-deploy/SKILL.md
└── docs/
    └── ADDING_SKILLS.md
```

## Per-Project Customization

Only file you must edit: `.agent/rules/01-project-context.md`

Don't need React? Delete `.agent/skills/react-frontend/` and `.agent/rules/03-typescript-standards.md`.
Don't need homelab? Delete `.agent/skills/homelab-ops/`.
'@ | Set-Content -Path "README.md" -Encoding UTF8

Write-Host ""
Write-Host "Done! Template files created:" -ForegroundColor Green
Get-ChildItem -Recurse -File | Select-Object -ExpandProperty FullName | ForEach-Object { $_.Replace((Get-Location).Path + "\", "") }
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Cyan
Write-Host "  1. Edit .agent\rules\01-project-context.md with your project details"
Write-Host "  2. Delete any skills you don't need"
Write-Host "  3. Open this folder in Antigravity"
